apiVersion: v1
kind: Pod
metadata:
  name: search-pod
  labels:
    name: search
spec:
  containers:
  - name: search
    image: kamranshaikh111/search:v1
    resources:
    ports:
      - containerPort: 80
