apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy-pod
          image : kamranshaikh111/kamran:v10 
          ports:
          - containerPort: 8080
          - containerPort: 8404
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  selector:
    app: haproxy
  ports:
    - name: port-80
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: port-90
      protocol: TCP
      port: 8084
      targetPort: 8404
      nodePort: 30001
  type: NodePort
