apiVersion: apps/v1
kind: Deployment
metadata:
  name: node2-api-deployment
  labels:
    app: node2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node2
  template:
    metadata:
      labels:
        app: node2
    spec:
      containers:
        - name: node2-pod
          image: kamranshaikh111/node2:v1
          ports: 
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node2-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: node2
  type: ClusterIP
