apiVersion: v1
kind: ReplicationController
metadata:
  name: search-repl-ctrl
spec:
  replicas: 2
  selector:
    app: search
  template:
    metadata:
      name: search-pod
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: kamranshaikh111/search:v1
        ports:
        - containerPort: 80
