apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deploy
  labels:
    app: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login-pod
        image: kamranshaikh111/login:v1
        ports:
        - containerPort: 80
