apiVersion: v1
kind: Pod
metadata:
  name: login-pod
  labels:
    name: login
spec:
  containers:
  - name: login
    image: kamranshaikh111/login:v1
    resources:
    ports:
      - containerPort: 80
