apiVersion: v1
kind: ReplicationController
metadata:
  name: login-repl-ctrl
spec:
  replicas: 0
  selector:
    app: login
  template:
    metadata:
      name: login-pod
      labels:
        app: login
    spec:
      containers:
      - name: login-pod
        image: kamranshaikh111/login:v1
        ports:
        - containerPort: 80
