apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: login-replica-set
  labels:
    app: login-pod-set
    tier: login
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: login
  template:
    metadata:
      labels:
        tier: login
    spec:
      containers:
      - name: login-pod
        image: kamranshaikh111/login:v1