apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: assignment4
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: kamranshaikh111/web:v1
          ports:
            - containerPort: 80
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: assignment4
  labels:
    app: web
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30001
      name: web
  selector:
    app: web
  type: NodePort