apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployement
  namespace : assignment1
  labels:
    app: haproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy-pod
          image: kamranshaikh111/hprox:v4
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace : assignment1
spec:
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
  type: NodePort

