apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployement
  namespace : assignment1
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-pod
          image:  kamranshaikh111/nod:v9
          ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace : assignment1
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: nodejs
  type: ClusterIP
