apiVersion: v1
kind: ReplicationController
metadata:
  name: submit-repl-ctrl
spec:
  replicas: 2
  selector:
    app: submit
  template:
    metadata:
      name: submit-pod
      labels:
        app: submit
    spec:
      containers:
      - name: submit
        image: kamranshaikh111/submit:v1
        ports:
        - containerPort: 80
